"""Add unique constraint to title

Revision ID: 2f2e40d9273d
Revises: 
Create Date: 2025-06-18 15:41:17.464949

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '2f2e40d9273d'
down_revision = None
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('menu_item', schema=None) as batch_op:
#         batch_op.create_unique_constraint('uq_menu_item_title', ['title'])

#     # ### end Alembic commands ###

def upgrade():
    conn = op.get_bind()
    inspector = inspect(conn)

    # Check if constraint already exists
    existing_constraints = [uc['name'] for uc in inspector.get_unique_constraints('menu_item')]
    if 'uq_menu_item_title' not in existing_constraints:
        with op.batch_alter_table('menu_item') as batch_op:
            batch_op.create_unique_constraint('uq_menu_item_title', ['title'])



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.drop_constraint('uq_menu_item_title', type_='unique')

    # ### end Alembic commands ###
