"""Add is_admin to user model

Revision ID: 7dbde4be086f
Revises: 2f2e40d9273d
Create Date: 2025-06-20 13:52:40.061839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '7dbde4be086f'
down_revision = '2f2e40d9273d'
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('user', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

#     # ### end Alembic commands ###

def upgrade():
    conn = op.get_bind()
    inspector = inspect(conn)

    existing_columns = [col['name'] for col in inspector.get_columns('user')]
    if 'is_admin' not in existing_columns:
        with op.batch_alter_table('user') as batch_op:
            batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
